name: Build and Push sleap-rtc-worker (Test Workflow)

on:
  push:
    branches-ignore:
      - main
    paths:
      - sleap_rtc/worker/**
      - .github/workflows/worker_test.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Git SHA
        id: get_sha
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Check disk space (before cleanup)
        run: df -h

      # Free up ~25-30GB of disk space by removing unused tools
      # Optimized to remove only essential unused components
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true          # ~10GB saved
          dotnet: true           # ~5GB saved
          haskell: false         # Skip, minimal savings
          large-packages: true   # ~8GB saved
          docker-images: true    # ~5GB saved, important for Docker builds
          swap-storage: false    # Skip, usually not needed

      - name: Check disk space (after cleanup)
        run: df -h

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Authenticate to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Build and push with layer caching for faster subsequent builds
      # First build: ~7-12 min, Cached builds: ~2-5 min (50-70% faster)
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./sleap_rtc/worker
          file: ./sleap_rtc/worker/Dockerfile
          platforms: linux/amd64
          push: true
          # Enable GitHub Actions cache for Docker layers
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/${{ github.repository_owner }}/sleap-rtc-worker:linux-amd64-test
            ghcr.io/${{ github.repository_owner }}/sleap-rtc-worker:linux-amd64-sleap-cuda-test
            ghcr.io/${{ github.repository_owner }}/sleap-rtc-worker:linux-amd64-${{ steps.get_sha.outputs.sha }}-test

      - name: Check disk space (after build)
        if: always()
        run: df -h
